// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NoteIt.Infrastructure.Data;

namespace NoteIt.Infrastructure.Data.Migrations
{
    [DbContext(typeof(NoteDbContext))]
    [Migration("20180810205927_GuidShared")]
    partial class GuidShared
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NoteIt.Core.Entities.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsPinned");

                    b.Property<bool>("IsShared");

                    b.Property<DateTime>("ModifiedAt");

                    b.Property<string>("Title")
                        .HasMaxLength(50);

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("NoteIt.Core.Entities.NoteContent", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<long>("NoteId");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.ToTable("Contents");
                });

            modelBuilder.Entity("NoteIt.Core.Entities.NoteContent", b =>
                {
                    b.HasOne("NoteIt.Core.Entities.Note", "Note")
                        .WithOne("Content")
                        .HasForeignKey("NoteIt.Core.Entities.NoteContent", "Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
